auth:
  auth-memory:
    users:
      foo:
        name: test
        password: test
store:
  memory:
    limit: 1000
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 10m
    max_fails: 20
    cache: false
packages:
  '@*/*':
    access: $all
    publish: $all
  '**':
    access: $all
    publish: $all
middlewares:
  audit:
    enabled: true
logs:
 - {type: stdout, format: pretty, level: trace}
