name: Publish & Install
# Temporarily disabled this workflow because the last step (installing from Verdaccio) is flaky and
# randomly failing despite numerous attempts to stabilize. Therefore this is not useful at
# the moment.
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
# on:
#   deployment
jobs:
  publish_install:
    runs-on: ${{ matrix.os }}
    # services:
    #   verdaccio:
    #     image: verdaccio/verdaccio:4
    #     ports:
    #       - 4873
    #     volumes:
    #       - /.github/workflows/verdaccio:/verdaccio/conf
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Verdaccio
      run: |
        npm install -g verdaccio
        npm install -g verdaccio-auth-memory
        npm install -g verdaccio-memory
        npm install -g npm-auth-to-token@1.0.0
        tmp_registry_log=`mktemp`
        mkdir -p $HOME/.config/verdaccio
        cp -v ./.github/workflows/verdaccio/config.yaml $HOME/.config/verdaccio/config.yaml
        nohup verdaccio --config $HOME/.config/verdaccio/config.yaml &>$tmp_registry_log &
        npm-auth-to-token -u test -p test -e test@test.com -r http://0.0.0.0:4873
    - name: Install & bootstrap
      run: |
        yarn config set unsafe-perm true
        yarn install
        yarn bootstrap
      env:
        CI: true
    - name: Publish to Verdaccio
      run: |
        yarn lerna publish prepatch --preid ci --no-push --no-git-tag-version --no-commit-hooks --force-publish "*" --yes --dist-tag ci --registry http://0.0.0.0:4873
    - name: Install via @vendure/create
      run: |
        mkdir -p $HOME/install
        cd $HOME/install
        npm set registry=http://0.0.0.0:4873
        npm dist-tag ls @vendure/create
        npx @vendure/create@ci test-app --ci --use-npm
    - name: Server smoke tests
      run: |
        cd $HOME/install/test-app
        npm run start &
        node $GITHUB_WORKSPACE/.github/workflows/scripts/smoke-tests
